/**
 * WebSocket subscription manager.
 *
 * Tracks connected clients and their workspace/chain filter subscriptions.
 * Used by the broadcaster to fan out server messages to interested clients only.
 */

import type { ServerWebSocket } from 'bun';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A per-client subscription with optional workspace and chain filters. */
export type Subscription = {
  id: string;
  clientId: string;
  workspaceId?: string;
  chainId?: string;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
};

/**
 * Return value when a duplicate subscription already exists.
 * Carries all `Subscription` fields plus `status: 'already_subscribed'`.
 */
export type DuplicateSubscriptionResult = Subscription & {
  status: 'already_subscribed';
};

/** Return value from a successful `unsubscribe` call. */
export type UnsubscribeResult =
  | { success: true }
  | { success: true; status: 'not_subscribed' };

/** An active WebSocket client tracked by the manager. */
export type WsClient = {
  id: string;
  /** Set of subscription IDs belonging to this client. */
  subscriptions: Set<string>;
  /** `Date.now()` timestamp of last client activity. */
  lastActivity: number;
  ws: ServerWebSocket<unknown>;
};

// ---------------------------------------------------------------------------
// SubscriptionManager
// ---------------------------------------------------------------------------

/**
 * Manages connected WebSocket clients and their topic subscriptions.
 *
 * - `addClient` / `removeClient`: lifecycle hooks called from `WsServer`
 * - `subscribe` / `unsubscribe`: respond to client commands
 * - `getInterestedClients`: used by `WsBroadcaster` to fan out messages
 * - `getClient`: direct lookup used by `WsBroadcaster` for targeted sends
 */
export class SubscriptionManager {
  private readonly clients = new Map<string, WsClient>();
  private readonly subscriptions = new Map<string, Subscription>();

  // -------------------------------------------------------------------------
  // Client lifecycle
  // -------------------------------------------------------------------------

  /**
   * Register a newly connected WebSocket client.
   *
   * @param clientId Unique identifier generated by `WsServer.generateClientId()`
   * @param ws       The live `ServerWebSocket` handle
   */
  addClient(clientId: string, ws: ServerWebSocket<unknown>): void {
    this.clients.set(clientId, {
      id: clientId,
      subscriptions: new Set(),
      lastActivity: Date.now(),
      ws,
    });
  }

  /**
   * Unregister a disconnected client and purge all of its subscriptions.
   *
   * No-op if `clientId` is not found.
   *
   * @param clientId The client to remove
   */
  removeClient(clientId: string): void {
    const client = this.clients.get(clientId);
    if (client === undefined) {
      return;
    }

    // Remove every subscription that belonged to this client.
    for (const subId of client.subscriptions) {
      this.subscriptions.delete(subId);
    }

    this.clients.delete(clientId);
  }

  // -------------------------------------------------------------------------
  // Subscription management
  // -------------------------------------------------------------------------

  /**
   * Create a new subscription for `clientId` with the given filter, or
   * return the existing subscription if an identical filter already exists.
   *
   * @param clientId Registered client
   * @param filter   Optional workspace / chain filters
   * @returns The new (or existing) `Subscription`, with `status: 'already_subscribed'` when deduped
   * @throws If `clientId` has not been registered via `addClient`
   */
  subscribe(
    clientId: string,
    filter: { workspaceId?: string; chainId?: string },
  ): Subscription | DuplicateSubscriptionResult {
    const client = this.clients.get(clientId);
    if (client === undefined) {
      throw new Error(`Client ${clientId} not found`);
    }

    // Check for a duplicate subscription (same workspaceId + chainId).
    for (const subId of client.subscriptions) {
      const existing = this.subscriptions.get(subId);
      if (
        existing !== undefined &&
        existing.workspaceId === filter.workspaceId &&
        existing.chainId === filter.chainId
      ) {
        return { ...existing, status: 'already_subscribed' };
      }
    }

    // Create a new subscription.
    const subId = `sub_${Date.now()}_${Math.random().toString(36).slice(2, 11)}`;
    const subscription: Subscription = {
      id: subId,
      clientId,
      workspaceId: filter.workspaceId,
      chainId: filter.chainId,
      createdAt: new Date().toISOString(),
    };

    this.subscriptions.set(subId, subscription);
    client.subscriptions.add(subId);
    client.lastActivity = Date.now();

    return subscription;
  }

  /**
   * Remove a subscription.
   *
   * Returns `{ success: true, status: 'not_subscribed' }` if the subscription
   * does not exist — this is a safe no-op, not an error.
   *
   * @param clientId       The owning client (used for Map cleanup)
   * @param subscriptionId The subscription to remove
   */
  unsubscribe(clientId: string, subscriptionId: string): UnsubscribeResult {
    const sub = this.subscriptions.get(subscriptionId);
    if (sub === undefined) {
      return { success: true, status: 'not_subscribed' };
    }

    this.subscriptions.delete(subscriptionId);

    const client = this.clients.get(clientId);
    if (client !== undefined) {
      client.subscriptions.delete(subscriptionId);
      client.lastActivity = Date.now();
    }

    return { success: true };
  }

  // -------------------------------------------------------------------------
  // Broadcast helpers
  // -------------------------------------------------------------------------

  /**
   * Return every unique `WsClient` that has a subscription matching the event.
   *
   * Matching rules (both must hold when the field is set on the subscription):
   * - If `sub.workspaceId` is set, it must equal `event.workspaceId`
   * - If `sub.chainId` is set, it must equal `event.chainId`
   *
   * Subscriptions with neither field set match any event (wildcard).
   *
   * @param event The broadcast event to match against
   * @returns Deduplicated list of interested `WsClient` instances
   */
  getInterestedClients(event: { workspaceId: string; chainId?: string }): WsClient[] {
    const seen = new Set<string>();
    const result: WsClient[] = [];

    for (const sub of this.subscriptions.values()) {
      // Workspace filter: skip if sub restricts workspace and it doesn't match.
      if (sub.workspaceId !== undefined && sub.workspaceId !== event.workspaceId) {
        continue;
      }

      // Chain filter: skip if sub restricts chain and it doesn't match.
      if (sub.chainId !== undefined && sub.chainId !== event.chainId) {
        continue;
      }

      const client = this.clients.get(sub.clientId);
      if (client !== undefined && !seen.has(client.id)) {
        seen.add(client.id);
        result.push(client);
      }
    }

    return result;
  }

  /**
   * Retrieve a single client by ID, or `undefined` if not connected.
   *
   * Used by `WsBroadcaster` to send targeted messages to the originating client.
   *
   * @param clientId The client to look up
   */
  getClient(clientId: string): WsClient | undefined {
    return this.clients.get(clientId);
  }
}
